# Generated by Django 5.1.1 on 2024-09-29 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('image', 'Image'), ('reading', 'Reading')], max_length=10)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idAsignature', models.IntegerField()),
                ('question', models.TextField()),
                ('options', models.TextField()),
                ('correctOption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.material')),
                ('idQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
            ],
        ),
    ]
