# Generated by Django 5.1.1 on 2024-09-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.ImageField(upload_to='materials/'),
        ),
    ]
