# Generated by Django 5.1.1 on 2024-09-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_material_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('image', 'Image')], max_length=10),
        ),
    ]
