# Generated by Django 5.1.1 on 2024-09-30 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_material_content_alter_material_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameAs', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='idAsignature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.asignature'),
        ),
    ]
