# Generated by Django 5.1.1 on 2024-09-30 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_asignature_alter_question_idasignature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asignature',
            new_name='Asignatures',
        ),
    ]
