# Generated by Django 5.1.1 on 2024-09-30 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_asignature_asignatures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asignatures',
            new_name='Asignature',
        ),
    ]
