# Generated by Django 5.1.1 on 2024-09-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_asignatures_asignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('writing', 'writing')], max_length=10),
        ),
    ]
