# Generated by Django 5.1.1 on 2024-09-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='writing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('reading', 'Reading')], max_length=10),
        ),
    ]
