# Generated by Django 5.1.1 on 2024-09-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_material_writing_alter_material_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='writing',
            new_name='text_content',
        ),
    ]
