# Generated by Django 5.1.1 on 2024-10-01 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_writing_material_text_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='type',
        ),
    ]
