# Generated by Django 5.1.1 on 2025-08-12 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='idAsignature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.asignature'),
        ),
    ]
