# Generated by Django 5.0.2 on 2026-06-18 13:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_material_idasignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='content',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
